haskell/alex

templates/wrappers.hs
tests/tokens_monadUserState_bytestring.x
tests/tokens_monad_bytestring.x

This fixes Issue #51.We make all ByteString wrappers keep track of the number of bytes yielded, so ByteString.length does not need to be called and the whole string does not need to be traversed.

Fix Issue #51

---

src/Main.hs

Like #50 but without the whitespace changes.

Added {-# OPTIONS_GHC -w #-} for tools like ghc-mod to stop reporting errors

---

Setup.lhs
alex.cabal
src/CharSet.hs
src/Data/Ranged/Boundaries.hs

Remove tabs from Setup.lhs to quiet down ghc 7.10. I also took liberty to remove tabs from cabal file although that didn't make any difference w.r.t. warnings.
Also, `DiscreteOrdered Word8` instance wan an orphan for some reason.

Fix some build-time warnings

---

examples/Makefile
src/Main.hs
templates/GenericTemplate.hs
templates/wrappers.hs
tests/Makefile

Well... almost. `-fno-warn-unused-binds` and `-fno-warn-missing-signatures` are still
needed. But we don't need `-w`. As I mentioned in [1], I think `-w` is a bad default, as it hides bugs in user code.
Requires a major version upgrade for the removal of `iUnbox`, and for not importing `Data.Char (ord)` in the generated code.
[1] https://github.com/simonmar/alex/commit/1eefcde22ba1bb9b51d523814415714e20f0761e#commitcomment-12002704

Fix all warnings in generated code

---

templates/wrappers.hs

I'm not sure why this wasn't noticed before (so maybe this is not a proper fix after all), but w/o it, `%wrapper "monad-bytestring"` is quite broken...

Fix type-signature for AlexAction w/ monad-bytestring

---

src/Main.hs
templates/wrappers.hs

for setting the desired size of the tab charachter ('\t'), it defaults
to 8 for backwards compatibility.

Adds flag '--tab-size=NUMBER / -s NUMBER'

---

doc/alex.xml
src/AbsSyn.hs
src/CharSet.hs
src/Main.hs
src/Parser.y
src/Scan.x
tests/tokens_bytestring.x
tests/tokens_bytestring_unicode.x
tests/tokens_monadUserState_bytestring.x
tests/tokens_monad_bytestring.x
tests/tokens_posn_bytestring.x
tests/tokens_strict_bytestring.x

This addresses the motivating use-case behind #66 by implementing a new
directive which is inspired by the existing %wrapper directive. The
encoding string is matched case insensitive. Supported examples:
%encoding "utf-8"
%encoding "iso-8859-1"
%encoding "UTF8"
%encoding "Latin1"
Moreover, some logic has been added to abort if the combination of CLI
`--latin1` flags and %encoding directives contradict each other. For
instance, setting `--latin1` on the command-line while requesting
`%encoding "utf8"` in the Alex script causes Alex to abort with an error.

Implement %encoding directive

---

src/Data/Ranged/RangedSet.hs

This makes the code compatible with some future GHC which will make
Semigroup a superclass of Monoid... there's of course no guarantee there
won't be other changes needed ;)
With these changes, alex compiles warning free under `-Wcompat`

Forward-compatibility for Semigroup/Monoid proposal

---

src/NFA.hs

Simple fix for a space leak. Reduces stack usage from 32K to < 1K.

Fix a space leak

---

templates/wrappers.hs

The ByteString wrappers were using paired calls to BS.head and BS.tail
which can be replaced a single call to BS.uncons.

ByteString wrappers: Use uncons instead of head/tail

---

templates/wrappers.hs
test.hs
tests/Makefile
tests/default_typeclass.x
tests/null.x
tests/simple.x
tests/tokens.x
tests/tokens_bytestring.x
tests/tokens_bytestring_unicode.x
tests/tokens_gscan.x
tests/tokens_monadUserState_bytestring.x
tests/tokens_monad_bytestring.x
tests/tokens_posn.x
tests/tokens_posn_bytestring.x
tests/tokens_strict_bytestring.x
tests/unicode.x

Warnings in the generated code makes it difficult to find warnings in user
code.
Tested with ghc 7.8.4, 7.10.3 and 8.0.1.

Fix compiler warnings in generated code

---

.travis.yml
README.md
alex.cabal

This updated travis file builds and tests alex with the last three
major releases of GHC.
By converting the README to markdown we get a travis build status
badge on the README.

Convert README to markdown and update travis file

---

templates/GenericTemplate.hs

I am not sure if this is appropriate, but I wanted to get rid of the compiler warnings for my Lexer. 
I have fixed them by indenting the code in `templates/GenericTemplate.hs`.
I have not seen any style guides in this repo so I reindented the cases such that they all align properly.
Kind regards,
Christophe De Troyer

Fix tab warnings in templates/GenericTemplate.hs

---

alex.cabal
src/Output.hs
tests/Makefile
tests/tokens_scan_user.x

The change fixes lexer generation failure for GHC lexer.
GHC lexer is special because it calls `alexScanUser`
to thread lexer state.
Added minimal test `tokens_scan_user.x`
to cover `alexScanUser` use.
Signature was reintroduced in commit 00431304aa18ada0a12aab43443023a86521f353
accidentally.
Fixes https://github.com/simonmar/alex/issues/98
Signed-off-by: Sergei Trofimovich <siarheit@google.com>

alex: fix generated type for 'alex_accept'

---

doc/alex.xml

I fixed a small bug in the pattern match of function `alexInputPrevChar` in the wrappers chapter.

fix tiny bug in pattern match

---

doc/alex.xml

Is the online documentation at https://www.haskell.org/alex/doc/html/index.html updated? I can still see typos that were fixed in 2013.

fixed grammatical and formatting errors

---

CHANGELOG.md
src/Output.hs
src/Scan.x
tests/tokens.x

Fix for #110 and for non-existing issue I diagnosed by the source code. It turns out that macro definition like `foo=[a-z]` was not handled correctly.

Recognize identifiers with multiple consecutive single quotes. Allow no spaces around equals sign in macro definitions.

---

doc/configure.ac

Allow Arch's makepkg to build and install documentation as expected.  Currently, on Arch, alex's document doesn't seem to be provided when alex is installed using the pacman package manager. (https://github.com/simonmar/alex/issues/113)

Add docbook xml path as currently found in Arch Linux

---

stack.yaml

generated by `stack init`, then removed noisy comments. `stack build` works as expected on Archlinux and FreeBSD.

add stack.yaml

---

.travis.yml
Makefile
README.md

This adds more checks and also adds two new targets
- `sdist-test`
- `sdist-test-only`
Which automate running the test-suite from within the source tarball.

Improve Makefile

---

templates/wrappers.hs
tests/Makefile
tests/default_typeclass.x

The utf8encode function always returned a list of at least one element,
but the type system didn't prove this, leading to spurious warnings when
taking the first element of the returned list. Fix this by returning a
tuple with the first element separate instead. (I would have used
Data.List.NonEmpty but it looks like we still support ancient GHC versions
that didn't yet have it.)

Fix warnings about non-exhaustive patterns

---

examples/haskell.x

The code in haskell.x was incorrectly detecting an error in the end of a comment when it had something like {-Comment --}.

Fix on nested_comment in haskell.x

---

src/CharSet.hs

For reasons not entirely clear, when compiling Alex with Bazel I get a warning about an invalid trigraph (it's probably doing its own CPP stuff or using its own options). It's not a fatal warning, but seems easy enough to avoid in this instance.

Avoid trigraph warning

---

tests/default_typeclass.x

This was added when we copied in StateT from MTL, but we don't actually
use it. Since the MonadFail Proposal was finished in GHC 8.8.1, it now
breaks compiling, so remove it.

Remove fail from default_typeclass test

---

templates/wrappers.hs

The GHC version detection didn't actually work right, resulting in the `__GLASGOW_HASKELL__ < 800` branch always being taken. This became apparent once I tried using GHC 8.8, as the fallback of `fail` inside `Monad` is no longer there, so it fails to compile. We need to fix this by playing the same sort of double-#define games that GenericTemplate.hs does. I plan to do that in a later PR but would like to unbreak this for now. Since there's been no release of Alex since this was added, this shouldn't qualify as a breaking change.
Reverts simonmar/alex#136

Revert "Add a proper implementation of fail to the Alex monad"

---

doc/alex.xml

Documents that monad wrappers expects you to define an `alexEOF` variable. This fixes #146. Hope that this will be useful for alex new users :)

Add `alexEOF` to monad wrapper docs. Fixes #146

---

src/DFAMin.hs

With GHC HEAD (8.11), build fails with
```
> /tmp/stack86151/alex-3.2.5/src/DFAMin.hs:35:17: error:
>     Suffix occurrence of @. For an as-pattern, remove the leading whitespace.
>    |       
> 35 | minimizeDFA  dfa@ DFA { dfa_start_states = starts,
>    |                 ^
```
This fixes that issue.

Fix build with GHC HEAD (8.11)

---

.gitignore
.travis.yml
alex.cabal

This simple PR extends `.travis.yml` to also test compilation of `alex` under ghc 8.6/8.

CI: test also ghc 8.6 and 8.8 on travis

---

alex.cabal
src/DFAMin.hs
tests/Makefile
tests/issue_71.x

[ #71 ] Fixed crash in DFAMin
DFA minimization used to crash on tokens of the form c* which produce
automata with only accepting states.  Considering the empty set of
non-accepting states as an equivalence class caused minimization to
crash with exception
Prelude.head: empty list
Now, DFA minimization succeeds.
There is still a problem with nullable tokens like c*.  Alex produces an
infinite token sequence at the end of the input.

Fixed crash in issue 71

---

src/Main.hs

The new error
```
file.x contains no lexer rules
```
can be tested with `file.x` containing
```
:- <0> { }
```
The previous error was
```
(Array.!): undefined array element
```
(I did not find a testsuite testing for error messages Alex gives, thus,
no test case with this commit.)

[ fixed #46 ] give proper error when no lexing rules

---

doc/README.md
doc/configure.ac

README.md gives brief instructions how to build the documentation.
There is a troubleshooting section helping if the DocBook XSL cannot be
found by `configure`.
configure.ac: Added XSL location for homebrew-installed docbook.

[ #128 ] Build instructions for the doc; xsl path for brew

---

alex.cabal
doc/alex.xml
src/Parser.y
src/Scan.x
tests/Makefile
tests/issue_141.x

Previously, the `r{n,m}` and related forms were restricted to single
digit numbers `n` and `m`.
We fix this by recognizing numbers of > 1 digits as NUM token and adding
rules to the regex parsing that also allows NUMs for `n` and `m`.
Previously, only CHAR was allowed, which subsumes single digits.

[ fixed #141 ] regex: allow arbitary repetitions

---

src/AbsSyn.hs
src/Main.hs
src/ParseMonad.hs
src/Parser.y

Changed `alex_scan_tkn` to return `AlexNone` instead of `AlexLastAcc` or
`AlexLastSkip` if length of newly processed input is still 0.
This fixes the problem that Alex would produce an infinite sequence of
tokens of length 0 when the DFA was stuck in a state accepting a
nullable token.
Now it will either produce EOF (if at end of input) or a lexer error (if
not at the end of input).  This is the intuitively expected behavior.

[ #71 ] warn about nullable regexs in the absence of start codes

---

.travis.yml
alex.cabal

Added ghc 8.10.1 to the travis matrix.
Also included GHC == 8.10.1 in the 'tested-with:' field.

[ travis ] test ghc 8.10 compilation

---

tests/default_typeclass.x

I'm getting the following error when trying to run the tests with GHC 9.0.1:
```
ghc -Wall -fwarn-incomplete-uni-patterns -fno-warn-missing-signatures -fno-warn-unused-imports -fno-warn-tabs -Werror -package array -package bytestring  default_typeclass.n.hs -o default_typeclass.n.bin
[1 of 1] Compiling Main             ( default_typeclass.n.hs, default_typeclass.n.o )
default_typeclass.x:136:7: error:
Found a binding for the ‘@’ operator in a pattern position.
Perhaps you meant an as-pattern, which must not be surrounded by whitespace
Possibly caused by a missing 'do'?
|
136 |     s @ AlexState { alex_errs = errs } <- get
|       ^
make: *** [Makefile:72: default_typeclass.n.bin] Error 1
/build/alex-3.2.6/dist/build/alex/alex  -g default_typeclass.x -o default_typeclass.g.hs
ghc -Wall …
```

tests/default_typeclass.x: remove spaces around as-pattern

---

tests/default_typeclass.x

Moving the definition of the `return` of the StateT monad to the
`Applicative` instance, to `pure`, fixes these warnings (which fail the
testsuite under `-Werror=noncanonical-monad-instances`):
Noncanonical ‘return’ definition detected
in the instance declaration for ‘Monad (StateT s m)’.
‘return’ will eventually be removed in favour of ‘pure’
Either remove definition for ‘return’ (recommended) or define as ‘return = pure’
Noncanonical ‘pure = return’ definition detected
in the instance declaration for ‘Applicative (StateT s m)’.
Move definition from ‘return’ to ‘pure’
PR ready, merge after squashing.

tests/default_typeclass: move def of return to pure

---

alex.cabal
src/Parser.y
src/Scan.x
tests/Makefile
tests/issue_197.x

Fix #197 by only lexing numeric literals in multiplicity expressions.
In issue #141, multiplicity annotations in regexes where extended to the general, multi-digit case `{nnn,mmm}`.  However, lexing numeric literals broke parsing of regexes like:
```
32|64
[01-89]
```
The solution here is to only lex numeric literals in a special lexerstate called `multiplicity` which is entered by the parser when parsing multiplicity braces `{nnn,mmm}`.
This restores alex' handling of digits as characters in the non-multiplicity situations.

Fix #197 by only lexing numeric literals in multiplicity expressions.

---

doc/index.rst

This was lost in the transition, it seems?

doc: Add back the abstract to contents page

---

doc/about.rst
doc/api.rst
doc/index.rst
doc/introduction.rst
doc/invoking.rst
doc/regex.rst
doc/syntax.rst

This might look weird at first, but unlike wrapping based on line
length, wrapping based on punction is "stable" across edits.  This is
important, because we it means we can have readable diffs without
drifting away from a (quasi) normal form.

Doc: Split lines by punctuation

---

.github/haskell-ci.patch
.github/workflows/haskell-ci.yml
DEVELOPER.md
alex.cabal
cabal.haskell-ci

Include GHC 9.6.1 alpha2 in CI.
Also:
- Install `alex` and `happy` from Ubuntu released packages (should be faster).
- Restrict CI to PRs and dedicated branches (avoid duplicate CI runs).
- Describe in DEVELOPER.md how to update the CI.

CI: bump to latest Haskell CI and latest GHC versions 

---

CHANGELOG.md
alex.cabal
data/AlexTemplate.hs

`offset` can be negative. We must check this before using it to index into `alex_check` array.
Caught with GHC's JS backend (native GHC would only segfault in rare circumstances).

Fix out-of-bound access to "alex_check" array

---

CHANGELOG.md
alex.cabal
data/AlexTemplate.hs

Amend PR #223 so that created source code does not need `LANGUAGE PatternGuards`.
Plan: release as v3.2.7.3 
Candidate: https://hackage.haskell.org/package/alex-3.2.7.3/candidate

v3.2.7.3 amend PR #223 so that it does not need `PatternGuards`

---

examples/Makefile
examples/tiger.x
examples/tiger/Literals.txt

Fix #180: example tiger.x: correct position of lexed string literal.
Previously, we would get e.g.
Lexeme class=STRING "Hello, world!" posn=1:19 string="\""
where the position points at the closing double quotes which are also
errorneously returned as lexed input.
Now, we produce
Lexeme class=STRING "Hello, world!" posn=1:5
with the correct starting position yet no information about the lexed input (`Nothing`).
To produce the lexed input, one needs more information in the lexer state.  
Not worth fixing, I deem, this is good enough as is as an example for Alex.

Fix #180: example tiger.x: correct position of lexed string literal

---

src/Util.hs

The function `Util.brack` is not used by any part of alex. A quick search through the tree with grep shows this.
Since alex doesn't expose an API and the function is not used internally, it might as well be removed from the module completely.
This pull request removes the function `brack` from the module `Util`.

Fix #228: Remove unused function `Util.brack`.

---

.github/workflows/haskell-ci.yml
CHANGELOG.md
src/Main.hs
tests/default_typeclass.x

Fix #125: put epilogue code last in the generated file.
This enables use of TemplateHaskell there.

Fix #125: put epilogue code last in the generated file.

---

.github/workflows/haskell-ci.yml
CHANGELOG.md
alex.cabal

Candidate at: https://hackage.haskell.org/package/alex-3.2.7.4/candidate

v3.2.7.4: Bump and finalize CHANGELOG

---

CHANGELOG.md
alex.cabal

Release candidate: https://hackage.haskell.org/package/alex-3.3.0.0/candidate
See also:
- #227

v3.3.0.0: Switch to four-digit version numbers

---

.github/workflows/haskell-ci-simple.yml
.github/workflows/haskell-ci.yml
alex.cabal
doc/about.rst
doc/contributing.rst

Rendering at:
- https://haskell-alex--241.org.readthedocs.build/en/241/about.html
- https://haskell-alex--241.org.readthedocs.build/en/241/contributing.html

Fix a broken link in docs plus some cosmetics

---

alex.cabal
data/AlexWrappers.hs
doc/api.rst
src/AbsSyn.hs
src/Main.hs
src/Output.hs
tests/Makefile
tests/posn_typeclass_strict_text.x
tests/strict_text_typeclass.x
tests/tokens_monadUserState_strict_text.x

This PR introduces the strict-text and posn-strict-text wrappers to allows working with Data.Text out of the box.
Implementation wise we could do a bit better by using Data.Text.Foreign.takeWord8 and avoiding the intermediate list of bytes in a codepoint but this will do for now.

Introduce strict-text and posn-strict-text wrappers and monadUserState-strict-text

---

CHANGELOG.md
src/Main.hs

Add option `--numeric-version` and rededicate `-v` to future `--verbose`

---

.gitignore
CHANGELOG.md
data/AlexTemplate.hs
src/Main.hs
tests/Makefile

Adding char after char order. For improving debug experience.

enhencing trace info of char

---

.github/workflows/emulated.yml
CHANGELOG.md
data/AlexTemplate.hs

Spurred by @Bodigrim in https://github.com/haskell/happy/pull/280#discussion_r1651705321, let's try having a bit more efficient code on `WORD_BIGENDIAN` architectures.
Mostly uploading this for CI, hoping there will be a big-endian machine to test the new code path.

Use byteSwapX# in WORDS_BIGENDIAN

---

alex.cabal
data/AlexTemplate.hs
tests/Makefile
tests/issue_262.x

If this error is thrown, it's difficult to debug: https://gitlab.haskell.org/ghc/ghc/-/issues/25609

Replace undefined with more descriptive error

---

CHANGELOG.md
alex.cabal

Candidate: https://hackage.haskell.org/package/alex-3.5.2.0/candidate

Bump to 3.5.2.0 and CHANGELOG

---

.github/workflows/emulated.yml

As recommended in https://github.com/haskell/alex/pull/270#issuecomment-2779671749, this PR bumps the version of `run-on-arch-action`, in the hope of getting rid of transient CI errors.

Fix transient CI failures

---

src/Parser.y.boot
src/Scan.x.boot

This PR is a small quality of life change.
As part of the tarball creation process, the Makefile `sdist` command creates two new files, `src/Scan.x.boot` and `src/Parser.y.boot`. Since we want them included in the resulting tarball, they are also listed in the `extra-source-files` in `alex.cabal`. This creates a bit of friction for developers: as those files do not exist in the repo itself, calls to `cabal install` fail.
To fix this, this PR adds two empty placeholder files. They do not impact any other workflow, but now allow `cabal install` to succeed.

add placeholder boot files to simplify local installs

---

alex.cabal
data/AlexTemplate.hs
tests/Makefile
tests/monadic_expr.x

This is the fix mentioned for 
- https://github.com/haskell/alex/issues/277.
Type inference on the unboxed types doesn't play so well with `-XImpredicativeTypes`, so, after creating testcases for it (one new handwritten one and converting preexisting ones by just using the language extension flag), this branch adds type annotations within C macros used in `AlexWrapper.hs`.
Closes #277.

tagToEnum# annotations in AlexWrapper C macros for -XImpredicativeTypes
